#include "AllegroRendererAPI.hpp"

namespace Nibbler
{

KeyCode ALLEGROKeyToKeyCode(int key)
{
	switch (key)
	{
		case ALLEGRO_KEY_SPACE:			return Key::Space;
		// case ALLEGRO_KEY_APOSTROPHE:	return Key::Apostrophe;
		case ALLEGRO_KEY_COMMA:			return Key::Comma;
		case ALLEGRO_KEY_MINUS:			return Key::Minus;
		// case ALLEGRO_KEY_PERIOD:		return Key::Period;
		case ALLEGRO_KEY_SLASH:			return Key::Slash;
		case ALLEGRO_KEY_0:				return Key::D0;
		case ALLEGRO_KEY_1:				return Key::D1;
		case ALLEGRO_KEY_2:				return Key::D2;
		case ALLEGRO_KEY_3:				return Key::D3;
		case ALLEGRO_KEY_4:				return Key::D4;
		case ALLEGRO_KEY_5:				return Key::D5;
		case ALLEGRO_KEY_6:				return Key::D6;
		case ALLEGRO_KEY_7:				return Key::D7;
		case ALLEGRO_KEY_8:				return Key::D8;
		case ALLEGRO_KEY_9:				return Key::D9;
		case ALLEGRO_KEY_SEMICOLON:		return Key::Semicolon;
		case ALLEGRO_KEY_EQUALS:		return Key::Equals;
		case ALLEGRO_KEY_A:				return Key::A;
		case ALLEGRO_KEY_B:				return Key::B;
		case ALLEGRO_KEY_C:				return Key::C;
		case ALLEGRO_KEY_D:				return Key::D;
		case ALLEGRO_KEY_E:				return Key::E;
		case ALLEGRO_KEY_F:				return Key::F;
		case ALLEGRO_KEY_G:				return Key::G;
		case ALLEGRO_KEY_H:				return Key::H;
		case ALLEGRO_KEY_I:				return Key::I;
		case ALLEGRO_KEY_J:				return Key::J;
		case ALLEGRO_KEY_K:				return Key::K;
		case ALLEGRO_KEY_L:				return Key::L;
		case ALLEGRO_KEY_M:				return Key::M;
		case ALLEGRO_KEY_N:				return Key::N;
		case ALLEGRO_KEY_O:				return Key::O;
		case ALLEGRO_KEY_P:				return Key::P;
		case ALLEGRO_KEY_Q:				return Key::Q;
		case ALLEGRO_KEY_R:				return Key::R;
		case ALLEGRO_KEY_S:				return Key::S;
		case ALLEGRO_KEY_T:				return Key::T;
		case ALLEGRO_KEY_U:				return Key::U;
		case ALLEGRO_KEY_V:				return Key::V;
		case ALLEGRO_KEY_W:				return Key::W;
		case ALLEGRO_KEY_X:				return Key::X;
		case ALLEGRO_KEY_Y:				return Key::Y;
		case ALLEGRO_KEY_Z:				return Key::Z;
		case ALLEGRO_KEY_OPENBRACE:		return Key::LeftBracket;
		case ALLEGRO_KEY_BACKSLASH:		return Key::Backslash;
		case ALLEGRO_KEY_CLOSEBRACE:	return Key::RightBracket;
		// case ALLEGRO_KEY_GRAVE_ACCENT:	return Key::GraveAccent;
		case ALLEGRO_KEY_ESCAPE:		return Key::Escape;
		case ALLEGRO_KEY_ENTER:			return Key::Return;
		case ALLEGRO_KEY_TAB:			return Key::Tab;
		case ALLEGRO_KEY_BACKSPACE:		return Key::Backspace;
		case ALLEGRO_KEY_INSERT:		return Key::Insert;
		case ALLEGRO_KEY_DELETE:		return Key::Delete;
		case ALLEGRO_KEY_RIGHT:			return Key::Right;
		case ALLEGRO_KEY_LEFT:			return Key::Left;
		case ALLEGRO_KEY_DOWN:			return Key::Down;
		case ALLEGRO_KEY_UP:			return Key::Up;
		// case ALLEGRO_KEY_PAGE_UP:		return Key::PageUp;
		// case ALLEGRO_KEY_PAGE_DOWN:		return Key::PageDown;
		case ALLEGRO_KEY_HOME:			return Key::Home;
		case ALLEGRO_KEY_END:			return Key::End;
		case ALLEGRO_KEY_CAPSLOCK:		return Key::CapsLock;
		case ALLEGRO_KEY_SCROLLLOCK:	return Key::ScrollLock;
		case ALLEGRO_KEY_NUMLOCK:		return Key::NumLockClear;
		case ALLEGRO_KEY_PRINTSCREEN:	return Key::PrintScreen;
		case ALLEGRO_KEY_PAUSE:			return Key::Pause;
		case ALLEGRO_KEY_F1:			return Key::F1;
		case ALLEGRO_KEY_F2:			return Key::F2;
		case ALLEGRO_KEY_F3:			return Key::F3;
		case ALLEGRO_KEY_F4:			return Key::F4;
		case ALLEGRO_KEY_F5:			return Key::F5;
		case ALLEGRO_KEY_F6:			return Key::F6;
		case ALLEGRO_KEY_F7:			return Key::F7;
		case ALLEGRO_KEY_F8:			return Key::F8;
		case ALLEGRO_KEY_F9:			return Key::F9;
		case ALLEGRO_KEY_F10:			return Key::F10;
		case ALLEGRO_KEY_F11:			return Key::F11;
		case ALLEGRO_KEY_F12:			return Key::F12;
		// case ALLEGRO_KEY_F13:			return Key::F13;
		// case ALLEGRO_KEY_F14:			return Key::F14;
		// case ALLEGRO_KEY_F15:			return Key::F15;
		// case ALLEGRO_KEY_F16:			return Key::F16;
		// case ALLEGRO_KEY_F17:			return Key::F17;
		// case ALLEGRO_KEY_F18:			return Key::F18;
		// case ALLEGRO_KEY_F19:			return Key::F19;
		// case ALLEGRO_KEY_F20:			return Key::F20;
		// case ALLEGRO_KEY_F21:			return Key::F21;
		// case ALLEGRO_KEY_F22:			return Key::F22;
		// case ALLEGRO_KEY_F23:			return Key::F23;
		// case ALLEGRO_KEY_F24:			return Key::F24;
		case ALLEGRO_KEY_PAD_0:			return Key::KP0;
		case ALLEGRO_KEY_PAD_1:			return Key::KP1;
		case ALLEGRO_KEY_PAD_2:			return Key::KP2;
		case ALLEGRO_KEY_PAD_3:			return Key::KP3;
		case ALLEGRO_KEY_PAD_4:			return Key::KP4;
		case ALLEGRO_KEY_PAD_5:			return Key::KP5;
		case ALLEGRO_KEY_PAD_6:			return Key::KP6;
		case ALLEGRO_KEY_PAD_7:			return Key::KP7;
		case ALLEGRO_KEY_PAD_8:			return Key::KP8;
		case ALLEGRO_KEY_PAD_9:			return Key::KP9;
		// case ALLEGRO_KEY_PAD_DECIMAL:	return Key::KPPeriod;
		case ALLEGRO_KEY_PAD_SLASH:	return Key::KPDivide;
		case ALLEGRO_KEY_PAD_ASTERISK:	return Key::KPMultiply;
		case ALLEGRO_KEY_PAD_MINUS:	return Key::KPSubtract;
		case ALLEGRO_KEY_PAD_PLUS:		return Key::KPAdd;
		case ALLEGRO_KEY_PAD_ENTER:		return Key::KPEnter;
		case ALLEGRO_KEY_PAD_EQUALS:		return Key::KPEquals;
		case ALLEGRO_KEY_LSHIFT:	return Key::LeftShift;
		case ALLEGRO_KEY_LCTRL:	return Key::LeftCtrl;
		case ALLEGRO_KEY_ALT:		return Key::LeftAlt;
		// case ALLEGRO_KEY_LEFT_SUPER:	return Key::LeftSuper;
		case ALLEGRO_KEY_RSHIFT:	return Key::RightShift;
		case ALLEGRO_KEY_RCTRL:return Key::RightCtrl;
		case ALLEGRO_KEY_ALTGR:		return Key::RightAlt;
		// case ALLEGRO_KEY_RIGHT_SUPER:	return Key::RightSuper;
		case ALLEGRO_KEY_MENU:			return Key::Menu;
		default: break;
	}
	return Key::None;
}

int KeyCodeToALLEGROKey(KeyCode key)
{
	switch (key)
	{
		case Key::Space:		return ALLEGRO_KEY_SPACE;
		// case Key::Apostrophe:	return ALLEGRO_KEY_APOSTROPHE;
		case Key::Comma:		return ALLEGRO_KEY_COMMA;
		case Key::Minus:		return ALLEGRO_KEY_MINUS;
		// case Key::Period:		return ALLEGRO_KEY_PERIOD;
		case Key::Slash:		return ALLEGRO_KEY_SLASH;
		case Key::D0:			return ALLEGRO_KEY_0;
		case Key::D1:			return ALLEGRO_KEY_1;
		case Key::D2:			return ALLEGRO_KEY_2;
		case Key::D3:			return ALLEGRO_KEY_3;
		case Key::D4:			return ALLEGRO_KEY_4;
		case Key::D5:			return ALLEGRO_KEY_5;
		case Key::D6:			return ALLEGRO_KEY_6;
		case Key::D7:			return ALLEGRO_KEY_7;
		case Key::D8:			return ALLEGRO_KEY_8;
		case Key::D9:			return ALLEGRO_KEY_9;
		case Key::Semicolon:	return ALLEGRO_KEY_SEMICOLON;
		case Key::Equals:		return ALLEGRO_KEY_EQUALS;
		case Key::A:			return ALLEGRO_KEY_A;
		case Key::B:			return ALLEGRO_KEY_B;
		case Key::C:			return ALLEGRO_KEY_C;
		case Key::D:			return ALLEGRO_KEY_D;
		case Key::E:			return ALLEGRO_KEY_E;
		case Key::F:			return ALLEGRO_KEY_F;
		case Key::G:			return ALLEGRO_KEY_G;
		case Key::H:			return ALLEGRO_KEY_H;
		case Key::I:			return ALLEGRO_KEY_I;
		case Key::J:			return ALLEGRO_KEY_J;
		case Key::K:			return ALLEGRO_KEY_K;
		case Key::L:			return ALLEGRO_KEY_L;
		case Key::M:			return ALLEGRO_KEY_M;
		case Key::N:			return ALLEGRO_KEY_N;
		case Key::O:			return ALLEGRO_KEY_O;
		case Key::P:			return ALLEGRO_KEY_P;
		case Key::Q:			return ALLEGRO_KEY_Q;
		case Key::R:			return ALLEGRO_KEY_R;
		case Key::S:			return ALLEGRO_KEY_S;
		case Key::T:			return ALLEGRO_KEY_T;
		case Key::U:			return ALLEGRO_KEY_U;
		case Key::V:			return ALLEGRO_KEY_V;
		case Key::W:			return ALLEGRO_KEY_W;
		case Key::X:			return ALLEGRO_KEY_X;
		case Key::Y:			return ALLEGRO_KEY_Y;
		case Key::Z:			return ALLEGRO_KEY_Z;
		case Key::LeftBracket:	return ALLEGRO_KEY_OPENBRACE;
		case Key::Backslash:	return ALLEGRO_KEY_BACKSLASH;
		case Key::RightBracket:	return ALLEGRO_KEY_CLOSEBRACE;
		// case Key::GraveAccent:	return ALLEGRO_KEY_GRAVE_ACCENT;
		case Key::Escape:		return ALLEGRO_KEY_ESCAPE;
		case Key::Return:		return ALLEGRO_KEY_ENTER;
		case Key::Tab:			return ALLEGRO_KEY_TAB;
		case Key::Backspace:	return ALLEGRO_KEY_BACKSPACE;
		case Key::Insert:		return ALLEGRO_KEY_INSERT;
		case Key::Delete:		return ALLEGRO_KEY_DELETE;
		case Key::Right:		return ALLEGRO_KEY_RIGHT;
		case Key::Left:			return ALLEGRO_KEY_LEFT;
		case Key::Down:			return ALLEGRO_KEY_DOWN;
		case Key::Up:			return ALLEGRO_KEY_UP;
		// case Key::PageUp:		return ALLEGRO_KEY_PAGE_UP;
		// case Key::PageDown:		return ALLEGRO_KEY_PAGE_DOWN;
		case Key::Home:			return ALLEGRO_KEY_HOME;
		case Key::End:			return ALLEGRO_KEY_END;
		case Key::CapsLock:		return ALLEGRO_KEY_CAPSLOCK;
		case Key::ScrollLock:	return ALLEGRO_KEY_SCROLLLOCK;
		case Key::NumLockClear:	return ALLEGRO_KEY_NUMLOCK;
		case Key::PrintScreen:	return ALLEGRO_KEY_PRINTSCREEN;
		case Key::Pause:		return ALLEGRO_KEY_PAUSE;
		case Key::F1:			return ALLEGRO_KEY_F1;
		case Key::F2:			return ALLEGRO_KEY_F2;
		case Key::F3:			return ALLEGRO_KEY_F3;
		case Key::F4:			return ALLEGRO_KEY_F4;
		case Key::F5:			return ALLEGRO_KEY_F5;
		case Key::F6:			return ALLEGRO_KEY_F6;
		case Key::F7:			return ALLEGRO_KEY_F7;
		case Key::F8:			return ALLEGRO_KEY_F8;
		case Key::F9:			return ALLEGRO_KEY_F9;
		case Key::F10:			return ALLEGRO_KEY_F10;
		case Key::F11:			return ALLEGRO_KEY_F11;
		case Key::F12:			return ALLEGRO_KEY_F12;
		// case Key::F13:			return ALLEGRO_KEY_F13;
		// case Key::F14:			return ALLEGRO_KEY_F14;
		// case Key::F15:			return ALLEGRO_KEY_F15;
		// case Key::F16:			return ALLEGRO_KEY_F16;
		// case Key::F17:			return ALLEGRO_KEY_F17;
		// case Key::F18:			return ALLEGRO_KEY_F18;
		// case Key::F19:			return ALLEGRO_KEY_F19;
		// case Key::F20:			return ALLEGRO_KEY_F20;
		// case Key::F21:			return ALLEGRO_KEY_F21;
		// case Key::F22:			return ALLEGRO_KEY_F22;
		// case Key::F23:			return ALLEGRO_KEY_F23;
		// case Key::F24:			return ALLEGRO_KEY_F24;
		case Key::KP0:			return ALLEGRO_KEY_PAD_0;
		case Key::KP1:			return ALLEGRO_KEY_PAD_1;
		case Key::KP2:			return ALLEGRO_KEY_PAD_2;
		case Key::KP3:			return ALLEGRO_KEY_PAD_3;
		case Key::KP4:			return ALLEGRO_KEY_PAD_4;
		case Key::KP5:			return ALLEGRO_KEY_PAD_5;
		case Key::KP6:			return ALLEGRO_KEY_PAD_6;
		case Key::KP7:			return ALLEGRO_KEY_PAD_7;
		case Key::KP8:			return ALLEGRO_KEY_PAD_8;
		case Key::KP9:			return ALLEGRO_KEY_PAD_9;
		// case Key::KPPeriod:		return ALLEGRO_KEY_PAD_DECIMAL;
		case Key::KPDivide:		return ALLEGRO_KEY_PAD_SLASH;
		case Key::KPMultiply:	return ALLEGRO_KEY_PAD_ASTERISK;
		case Key::KPSubtract:	return ALLEGRO_KEY_PAD_MINUS;
		case Key::KPAdd:		return ALLEGRO_KEY_PAD_PLUS;
		case Key::KPEnter:		return ALLEGRO_KEY_PAD_ENTER;
		case Key::KPEquals:		return ALLEGRO_KEY_PAD_EQUALS;
		case Key::LeftShift:	return ALLEGRO_KEY_LSHIFT;
		case Key::LeftCtrl:		return ALLEGRO_KEY_LCTRL;
		case Key::LeftAlt:		return ALLEGRO_KEY_ALT;
		// case Key::LeftSuper:	return ALLEGRO_KEY_LEFT_SUPER;
		case Key::RightShift:	return ALLEGRO_KEY_RSHIFT;
		case Key::RightCtrl:	return ALLEGRO_KEY_RCTRL;
		case Key::RightAlt:		return ALLEGRO_KEY_ALTGR;
		// case Key::RightSuper:	return ALLEGRO_KEY_RIGHT_SUPER;
		case Key::Menu:			return ALLEGRO_KEY_MENU;
		default: break;
	}
	return 0;
}

} // Nibbler
